In [1]:
import numpy as np

In [44]:
np.random.seed(42)

In [60]:
hyderabad = np.random.uniform(low = -10, high = 40, size = 365)

In [56]:
np.round(hyderabad[:5], 2)

array([ 9.31, 38.06, 35.27, -0.21, -6.53])

In [66]:
print(np.round(hyderabad[:365],2))

[-1.79 30.73 23.26 16.15  7.94 33.86  9.62 30.83 11.96  8.85 13.13  5.07
 27.38 15.14  1.61 34.98  9.19 17.18 35.32 21.21 -4.16 36.99 21.39  6.75
 -3.04 29.7  21.   16.67 34.69 29.43 -2.42  5.59  2.42 27.2  -8.32 18.49
 28.12 33.84  7.1  31.06 -4.47 32.32 -3.63  9.86 29.86 -2.5   1.46 26.11
 26.   22.06 24.7  17.14  2.59  7.28 -0.92 35.42 19.17 10.04 13.1  37.36
 -2.33 19.31 15.29 20.57 -9.09 33.61 36.61 18.26 24.83 36.12 25.36 -2.37
 18.81 20.34 11.21 26.82 36.72 36.28 12.54 -4.34 39.24 31.94 -3.77 36.04
 33.49 15.94 19.56  9.95 -7.26  6.76 30.14 -9.77  6.67  9.91 16.87 35.99
  7.32  7.35 26.88 12.61  1.23 12.62 -2.96 -1.18 14.92 10.95 35.74  8.12
 19.03 21.61 -9.35 23.18 -1.1  38.05 -2.57 10.73 -5.73 39.84 15.11 19.77
 -6.65 27.5   0.5  34.9   0.26 -0.47 -8.17 13.6  18.24 -6.71 28.78 12.66
 16.22 12.04 10.04 17.98 -2.24 -0.9  33.09 37.31  8.67  3.54 22.2  10.44
 -8.73 -2.19 25.8  22.95 -8.65  1.1   1.55 23.59 -9.01 -4.79 30.   -1.07
 22.64  1.91 -5.03  2.16 26.11 32.78 31.51  9.86 23

In [30]:
#Basic Analysis of this randomly generated data 

In [84]:
mean = np.mean(hyderabad)

In [86]:
mean

np.float64(14.920193943081332)

In [88]:
median = np.median(hyderabad)

In [90]:
median

np.float64(14.918388636973987)

In [92]:
std = np.std(hyderabad)

In [94]:
std

np.float64(14.501744048785595)

In [102]:
#Hottest and coolest temperatures

In [104]:
max = np.max(hyderabad)

In [106]:
max

np.float64(39.89670552666687)

In [108]:
min = np.min(hyderabad)

In [110]:
min

np.float64(-9.768398849769858)

In [120]:
argmax = np.argmax(hyderabad)

In [122]:
argmax

np.int64(324)

In [124]:
#For heatwave days >35

In [136]:
temp = hyderabad>35

In [152]:
temp1 = hyderabad[temp]

In [154]:
temp2 = temp1.size

In [156]:
temp2

38

In [158]:
#For cooler days<0

In [160]:
cool = hyderabad < 0

In [162]:
cool1 = hyderabad[cool]

In [164]:
cool2 = cool1.size

In [166]:
cool2

72

In [168]:
temp3 = np.array(temp1)

In [170]:
temp3

array([35.32360555, 36.99160618, 35.42252807, 37.36416698, 36.60591412,
       36.12496906, 36.71835074, 36.27842565, 39.24205995, 36.04209413,
       35.99278082, 35.74229505, 38.05351587, 39.84371259, 37.30577311,
       37.42266535, 39.22010904, 35.71494033, 35.00093209, 35.7205973 ,
       36.84148697, 35.86567877, 37.51186769, 39.3834004 , 37.20296698,
       36.26241587, 35.77441488, 36.21980977, 38.55291226, 37.21332446,
       36.95338493, 39.89670553, 39.20417346, 39.38611949, 37.4980592 ,
       37.23660111, 39.55843131, 37.13658871])

In [172]:
normalized_temp = (hyderabad - min) / (max - min)

In [174]:
normalized_temp

array([0.1607102 , 0.8154042 , 0.66501944, 0.52192924, 0.35658685,
       0.87845231, 0.39042814, 0.81744258, 0.43743277, 0.37482294,
       0.46113641, 0.29874683, 0.74798731, 0.50144702, 0.22911527,
       0.90097722, 0.38181657, 0.54255482, 0.90792127, 0.62378402,
       0.11302304, 0.94150623, 0.62727748, 0.33250065, 0.13554794,
       0.79471611, 0.6195907 , 0.532395  , 0.89525691, 0.78925153,
       0.14803438, 0.30916078, 0.24550146, 0.74429952, 0.02909529,
       0.56906924, 0.76293675, 0.87801448, 0.33972518, 0.82213185,
       0.10671448, 0.84749673, 0.12368507, 0.39530297, 0.79800833,
       0.14626508, 0.226134  , 0.72245952, 0.72022854, 0.64080768,
       0.69396454, 0.54172082, 0.2488337 , 0.34336379, 0.17815899,
       0.90991306, 0.58266239, 0.39889113, 0.46045789, 0.94900769,
       0.14972221, 0.58551957, 0.50463667, 0.61091406, 0.01356905,
       0.87334145, 0.93374037, 0.56428066, 0.69668514, 0.92405661,
       0.70734434, 0.14890437, 0.57551106, 0.60614292, 0.42232

In [180]:
normalized_temp1 = np.round(normalized_temp[:365],2)

In [182]:
normalized_temp1

array([0.16, 0.82, 0.67, 0.52, 0.36, 0.88, 0.39, 0.82, 0.44, 0.37, 0.46,
       0.3 , 0.75, 0.5 , 0.23, 0.9 , 0.38, 0.54, 0.91, 0.62, 0.11, 0.94,
       0.63, 0.33, 0.14, 0.79, 0.62, 0.53, 0.9 , 0.79, 0.15, 0.31, 0.25,
       0.74, 0.03, 0.57, 0.76, 0.88, 0.34, 0.82, 0.11, 0.85, 0.12, 0.4 ,
       0.8 , 0.15, 0.23, 0.72, 0.72, 0.64, 0.69, 0.54, 0.25, 0.34, 0.18,
       0.91, 0.58, 0.4 , 0.46, 0.95, 0.15, 0.59, 0.5 , 0.61, 0.01, 0.87,
       0.93, 0.56, 0.7 , 0.92, 0.71, 0.15, 0.58, 0.61, 0.42, 0.74, 0.94,
       0.93, 0.45, 0.11, 0.99, 0.84, 0.12, 0.92, 0.87, 0.52, 0.59, 0.4 ,
       0.05, 0.33, 0.8 , 0.  , 0.33, 0.4 , 0.54, 0.92, 0.34, 0.34, 0.74,
       0.45, 0.22, 0.45, 0.14, 0.17, 0.5 , 0.42, 0.92, 0.36, 0.58, 0.63,
       0.01, 0.66, 0.17, 0.96, 0.15, 0.41, 0.08, 1.  , 0.5 , 0.59, 0.06,
       0.75, 0.21, 0.9 , 0.2 , 0.19, 0.03, 0.47, 0.56, 0.06, 0.78, 0.45,
       0.52, 0.44, 0.4 , 0.56, 0.15, 0.18, 0.86, 0.95, 0.37, 0.27, 0.64,
       0.41, 0.02, 0.15, 0.72, 0.66, 0.02, 0.22, 0.

In [184]:
normalized_temp_min = np.min(normalized_temp1)

In [186]:
normalized_temp_min

np.float64(0.0)

In [190]:
normalized_temp_max = np.max(normalized_temp1)

In [192]:
normalized_temp_max

np.float64(1.0)